format = """
[](#B48EAD)\
$os\
$username\
[](bg:#BF616A fg:#B48EAD)\
$directory\
[](fg:#BF616A bg:#D08770)\
$git_branch\
$git_status\
[](fg:#D08770 bg:#81A1C1)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#81A1C1 bg:#8FBCBB)\
$docker_context\
[](fg:#8FBCBB bg:#5E81AC)\
$time\
[ ](fg:#5E81AC)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#B48EAD"
style_root = "bg:#B48EAD"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#B48EAD"
disabled = true # Disabled by default

[directory]
style = "bg:#BF616A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#8FBCBB"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#D08770"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#D08770"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#81A1C1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#5E81AC"
format = '[ ♥ $time ]($style)'
